POST http://localhost:3100/api/tools/cc_bitrix_jaguar?dni=72377685&un=elp&periodo=2025-C&pestudio=SI

### 
GET http://api.lapontificia.edu.pe/ping

###
POST https://api.lapontificia.edu.pe/api/tools/cc_bitrix_jaguar
content-type: application/json

{
  "firstName": "Bonnie",
  "lastName": "Lass",
  "email": "bonnie.lass@mycompany.com",
  "password": "password",
  "role": "admin"
}

###  get deal
POST https://lapontificia.bitrix24.es/rest/30965/1bjbl9ir52fuew6b/crm.deal.get.json
content-type: application/json

{
  "ID": 67497
}

### get client
POST https://lapontificia.bitrix24.es/rest/30965/1bjbl9ir52fuew6b/crm.contact.get.json
content-type: application/json

{
  "ID": "59241"
}
